### ISSUE TITLE
Update readme to include complete and correct information.

### ISSUE THREAD

**Issue by shoaibkalsekar** [pranjalk/dx#1]
Seems like the readme has some setup information missing. The `Tech Stack` suggests that there is,
- **Mysql**, however there is no information/command/link on how to set it up or which version is compatible, etc.
- **ReactJs**, however the package.json file does not include entry of `react` package.
- **NodeJs** - Any specific version?
- **jQuery** - Absolutely not required and has to be removed.

Let package.json have exact version numbers for packages as used in development to ensure that the application is setup, anywhere, has the same packages(versions).

**Comment by pranjalk** [comment]
Created a pull request for fixes https://github.com/pranjalk/dx/pull/2

**Comment by pranjalk** [comment]
closing issue
